module.exports = {
  apps: [
    {
      name: "skin1004-prod",
      script: "/home/skin1004/AI_Agent/venv/bin/python3",
      args: "-X utf8 -m uvicorn app.main:app --host 0.0.0.0 --port 3000 --workers 4",
      cwd: "/home/skin1004/AI_Agent",
      interpreter: "none",
      env: {
        PORT: "3000",
        PYTHONIOENCODING: "utf-8",
        PYTHONUTF8: "1",
        PATH: "/home/skin1004/AI_Agent/venv/bin:/usr/bin:/bin",
        GOOGLE_APPLICATION_CREDENTIALS: "/home/skin1004/keys/skin1004-319714-60527c477460.json"
      },
      autorestart: true,
      max_memory_restart: "2G",
      restart_delay: 3000,
      max_restarts: 50,
      min_uptime: "10s",
      exp_backoff_restart_delay: 1000,
      out_file: "logs/pm2-prod-out.log",
      error_file: "logs/pm2-prod-error.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "skin1004-dev",
      script: "/home/skin1004/AI_Agent/venv/bin/python3",
      args: "-X utf8 -m uvicorn app.main:app --host 0.0.0.0 --port 3001 --workers 2",
      cwd: "/home/skin1004/AI_Agent",
      interpreter: "none",
      env: {
        PORT: "3001",
        PYTHONIOENCODING: "utf-8",
        PYTHONUTF8: "1",
        PATH: "/home/skin1004/AI_Agent/venv/bin:/usr/bin:/bin",
        GOOGLE_APPLICATION_CREDENTIALS: "/home/skin1004/keys/skin1004-319714-60527c477460.json"
      },
      autorestart: true,
      max_memory_restart: "2G",
      restart_delay: 3000,
      max_restarts: 50,
      min_uptime: "10s",
      exp_backoff_restart_delay: 1000,
      out_file: "logs/pm2-dev-out.log",
      error_file: "logs/pm2-dev-error.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "skin1004-watchdog",
      script: "/home/skin1004/AI_Agent/venv/bin/python3",
      args: "scripts/server_watchdog.py",
      cwd: "/home/skin1004/AI_Agent",
      interpreter: "none",
      env: {
        PYTHONIOENCODING: "utf-8",
        PATH: "/home/skin1004/AI_Agent/venv/bin:/usr/bin:/bin"
      },
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 10,
      out_file: "logs/watchdog-out.log",
      error_file: "logs/watchdog-error.log",
      merge_logs: true,
      time: true,
    },
  ]
};
