"""LangGraph state definitions for the agent workflow."""

from typing import List, Literal, Optional

from typing_extensions import TypedDict


class AgentState(TypedDict):
    """Main state schema for the LangGraph workflow.

    Attributes:
        query: Original user question.
        route_type: Classified intent type.
        generated_sql: SQL generated by the Text-to-SQL agent.
        sql_valid: Whether the SQL passed security validation.
        sql_result: Query execution results.
        retrieved_docs: Documents retrieved by RAG.
        doc_relevance: Whether retrieved docs are relevant.
        web_search_results: Results from Tavily web search (CRAG fallback).
        answer: Final generated answer.
        needs_retry: Whether the answer needs regeneration.
        retry_count: Number of retries performed.
        error: Error message if something went wrong.
        messages: Conversation history for multi-turn.
    """

    query: str
    route_type: Literal["text_to_sql", "rag", "direct_llm", "multi_agent"]

    # Text-to-SQL
    generated_sql: Optional[str]
    sql_valid: Optional[bool]
    sql_result: Optional[list]

    # RAG
    retrieved_docs: Optional[List[str]]
    doc_relevance: Optional[Literal["yes", "no"]]
    web_search_results: Optional[List[str]]

    # Output
    answer: str
    needs_retry: bool
    retry_count: int

    # Error handling
    error: Optional[str]

    # Conversation
    messages: Optional[List[dict]]
